#!/usr/bin/env bash
# Install Nginx
# Configure Nginx server so that /redirect_me is redirecting to another page.
# Configure Nginx server to give error 404 page
# Start/ Restart server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;

    location / {
            try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location /404.html {
        internal;
    }

    if (\$request_filename ~ redirect_me){
        rewrite ^ https:/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}
"
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "$_config" > /etc/nginx/sites-available/default

if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;