#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server. 

load_balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 238459-web-01 52.205.83.252:80 check
    server 238459-web-02 54.174.86.201:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy

#append custom configuration to HAProxy configuration file
# and backup original config file
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$load_balancer" >> /etc/haproxy/haproxy.cfg

# Validate HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

#restart HAProxy
service haproxy restart