#!/usr/bin/env bash
#find out what’s keeping your Ubuntu container’s Nginx installatio
#from listening on port 80
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
