#!/usr/bin/env bash
#find out what’s keeping your Ubuntu container’s Nginx
#installation from listening on port 80
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
pgrep nginx | xargs kill -1