#!/usr/bin/env bash
# Displays numbers from 1 to 20. 
# Dispalys "4" then "badluck from china",
# Displays "9" then "Bad luck from Japan"
# Displays "17" then "bad luck from Italy"

i="1"
while [ $i -le 20 ]; do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	i=$((i+1))
done

	
	
